name: Docker Image CI
run-name: Building hello image

on: 
  push:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: code
      run: docker build . --file Dockerfile --tag hello
    - name: Running a Docker container
      run: docker run hello
